#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# so, aliases for some programs are here, as follows:

# youtube-dl
alias \
 yt='yt-dlp --embed-thumbnail --embed-metadata --add-metadata -i' \
 yta='yt -x -f bestaudio/best -o "~/Musica/dl-music/%(title)s.%(ext)s"' \
 ytp='yt -x -f bestaudio/best -o "~/Videos/Podcast/%(title)s.%(ext)s"' \
 ytn='yt --embed-thumbnail --embed-metadata -o "./%(title)s.%(ext)s"'

# bashrc/other configs
alias \
 nc="$EDITOR ~/.config/$EDITOR/init.vim" \
 s="$EDITOR ~/.config/sxhkd/sxhkdrc"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
  rmd="rmdir -v" \
  du="du -h" \
  rt="rsync -Paz" \
  ft="rt --no-recursive"

# ffmpeg commands
alias \
	ffmpeg="ffmpeg -hide_banner" \
  ffconvert="find -maxdepth 1 -mindepth 1 -type f -name '*.mkv' -print -exec sh -c 'i="{}"; ffmpeg -i "$i" -c:v libx264 -crf 22 "${i%.mkv}".mp4' \;"

# These common commands are just too long! Abbreviate them.
alias \
	z="zathura" \
        ka="killall" \
        lf="lfub" \
        g="git" \
	      i="sxiv -q -a -t" \
	      sdn="sudo shutdown -h now" \
        mk="sudo make install" \
        df='df -lH ' \
        n="neomutt" \
        mps="mpv --shuffle" \
        p="sudo pacman" \
        pn="sudo pacman -S --needed" \
        pu="sudo pacman -Syu" \
        pa="paru" \
        ne="neofetch" \
        v="$EDITOR" \
        t="tmux" \
        tn="tmux new-session -swk" \
        h="htop" \
        c="cointop" \
        src="source ~/.config/shell/profile && source ~/.zshrc && source ~/.config/shell/aliasrc"

# enable color support of ls and also add handy aliases
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    datecheck='ls -l | grep "$(if [[ "$(date "+%-d")" -lt 10 ]]; then date "+%b  %-d"; else date "+%b %-d"; fi)"' \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    fgrep="fgrep --color=auto" \
    egrep="egrep --color=auto" \
    diff="diff --color=auto" \
    ip="ip --color=auto"

# alias \
	# ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"

# java related alias
alias \
    tscp="tsc -p tsconfig.json"

con() { cd ~/.config; $EDITOR $(fzf) ;}

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}
