#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# so, aliases for some programs are here, as follows:

# youtube-dl
alias \
 yt='yt-dlp --embed-thumbnail --embed-metadata --add-metadata -i' \
 yta='yt -x -f bestaudio/best -o "~/Musica/dl-music/%(title)s.%(ext)s"' \
 ytp='yt -x -f bestaudio/best -o "~/Videos/Podcast/%(title)s.%(ext)s"' \
 ytn='yt --embed-thumbnail --embed-metadata -o "./%(title)s.%(ext)s"'

# bashrc/other configs
alias \
 nc="$EDITOR ~/.config/$EDITOR/init.vim" \
 s="$EDITOR ~/.config/sxhkd/sxhkdrc"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
        rmd="rmdir -v" \
	ffmpeg="ffmpeg -hide_banner" \
        du="du -h"

# These common commands are just too long! Abbreviate them.
alias \
	z="zathura" \
        ka="killall" \
        lf="lfub" \
        g="git" \
	i="sxiv -q -a -t" \
	sdn="sudo shutdown -h now" \
        mk="sudo make install" \
        df='df -lH ' \
        n="neomutt" \
        mps="mpv --shuffle" \
        pn="sudo pacman -S --needed" \
        v="$EDITOR" \
        src="source ~/.config/shell/profile && source .zshrc"

# enable color support of ls and also add handy aliases
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    fgrep="fgrep --color=auto" \
    egrep="egrep --color=auto" \
    diff="diff --color=auto" \
    ip="ip --color=auto"

# alias \
	# ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"

# /dev/null aliases (no annoying stdout from programs)
alias  \
        bra='$BROWSER > /dev/null 2>&1' \
        pm="pcmanfm > /dev/null 2>&1" \
	a='anki > /dev/null 2>&1 &'

con() { cd ~/.config; $EDITOR $(fzf) ;}

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}
