#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
inactivity &            # lock and suspend screen if inactive for too long
battery-status &             # notify when battery is less than 20
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
# kill $(pidof xfce4-notifyd)

autostart="mpd transmission-daemon xcompmgr unclutter dunst udiskie pulseaudio"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

export GTK_IM_MODULE='fcitx5'
export QT_IM_MODULE='fcitx5'
export SDL_IM_MODULE='fcitx5'
export XMODIFIERS=@im='fcitx5'

# export GTK_IM_MODULE DEFAULT=xim
# export QT_IM_MODULE  DEFAULT=xim
