#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
# setbg &			# set the background with the `setbg` script
# lockscreen &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
kill $(pidof xfce4-notifyd)

autostart="fcitx mpd xcompmgr unclutter sxhkd -m 1 redshift numlockx dunst"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

export GTK_IM_MODULE='ibus' &
export QT_IM_MODULE='ibus' &
export QT4_IM_MODULE='xim' &
export CLUTTER_IM_MODULE='xim' &
export SDL_IM_MODULE='ibus' &
export XMODIFIERS='@im=ibus'
