[main]
font=JetBrainsMono Nerd Font Mono:size=12
pad=12x18
term=foot
initial-window-size-chars=190x60

app-id=foot
title=pie nwn
locked-title=no

[scrollback]
lines=16384
indicator-format=percentage

[colors-dark]
alpha=0.80

# -*- conf -*-
# Nord Color Palette

background=2e3440
foreground=d8dee9

regular0=3b4252
regular1=bf616a
regular2=a3be8c
regular3=ebcb8b
regular4=81a1c1
regular5=b48ead
regular6=88c0d0
regular7=e5e9f0
bright0=4c566a
bright1=bf616a
bright2=a3be8c
bright3=ebcb8b
bright4=81a1c1
bright5=b48ead
bright6=8fbcbb
bright7=eceff4

[key-bindings]
font-increase=Control+Shift+k
font-decrease=Control+Shift+j
font-reset=Control+0
search-start=Control+Shift+f
clipboard-copy=Alt+c
clipboard-paste=Alt+v
scrollback-up-half-page=Control+k
scrollback-down-half-page=Control+j
show-urls-launch=Control+Shift+l

