#!/bin/sh

freedom='GNU not UNIX ; GNU plus Linux'

echo $freedom

# Replace first occurrence of pattern with string
echo "${freedom/GNU/Gahnoo}"
# one forward slash means first instance of
# two forward slashes mean all
# kinda like g in sed "s//g"

# Remove first match of pattern
echo "${freedom/* ; /}"
# using regex

freedom='GNU Not Unix ; GNU is Not Unix ; Gahnoo slash Linaks ; GNU/Linux'

echo $freedom

# Remove all occurrences of pattern
echo "${freedom//* ; /}"
