#!/bin/sh
var="pitoncha culo dduan"
torrent="unarchivo_peer.torrent"

echo -n "The variable is a string: "
echo $var

# Porcentage sign searches from the very end
# Glob match (asterisk) with one porcentage sign deletes nothing, as in, it tries to delete as little as possible
# First one deletes everything from the last word until it finds its first d. The second one deletes everything from the last word until it finds a space. This is the non-greedy version, i.e, it'll consume as little as possible.

echo -n "Remove prefix (non greedy): "
echo "${var%d*}" && echo "${var% *}"

# Glob match (asterisk) with two porcentage signs deletes anything, as in, it tries to delete as much as possible
# This one deletes everything it can from the last word until it finds a d, in which case it's going to remove both of them. Then, it's also going to delete as many spaces as possible, from the last word onwards (so, the two spaces). This is greedy, i.e, it'll consume as much as possible.

echo -n "Remove prefix (greedy): "
echo "${var%%d*}" && echo "${var%% *}"

# Pound sign searches from the very beginning
# Glob match (asterisk) with one pound sign deletes nothing, as in, it tries to delete as little as possible
echo -n "Remove suffix (non greedy): "
# First one deletes everything from the first word until it finds its first d. The second one deletes everything from the first word until it finds a space. This is the non-greedy version, i.e, it'll consume as little as possible.
echo "${var#*d}" && echo "${var#* }"

# Glob match (asterisk) with two pound signs deletes anything, as in, it tries to delete as much as possible
# This one deletes everything it can from the first word until it finds a d, in which case it's going to remove both of them. Then, it's also going to delete as many spaces as possible, from the first word onwards (so, the two spaces). This is greedy, i.e, it'll consume as much as possible.
echo -n "Remove suffix (greedy): "
echo "${var##*d}" && echo "${var##* }"

echo "${torrent#*.}"
