general {
    lock_cmd = pidof swaylock || swaylock -f
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = wlr-randr --output eDP-1 --on
}


listener {
    timeout = 300                                # 5min
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 600                                 # 10min
    on-timeout = wlr-randr --output eDP-1 --off && loginctl lock-session
    on-resume = wlr-randr --output eDP-1 --on
}
