#!/bin/sh

pgrep -x sxhkd || sxhkd &
pgrep -x nm-applet || nm-applet &
pgrep -x redshift-gtk || redshift-gtk &
numlockx on &
inactivity.sh &
fcitx5 -dr &
$HOME/.config/polybar/launch.sh
$HOME/.config/x11/xinitrc
xsetroot -cursor_name left_ptr

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

### Monitors ###
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9

### BSPWM config ###
bspc config border_width          2
bspc config window_gap            5
bspc config top_padding           22
bspc config bottom_padding        2
bspc config left_padding          2
bspc config right_padding         2
bspc config split_ratio           0.50
bspc config single_monocle        false
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# bspc config focus_by_distance     true
# bspc config click_to_focus        true
bspc config focus_follows_pointer true

#BSPWM coloring
bspc config normal_border_color		"#928374"
bspc config active_border_color		"#282828"
bspc config focused_border_color	"#fb4934"
bspc config presel_feedback_color	"#98971a"
bspc config urgent_border_color 	"#cc241d"


# Rules for windows
bspc rule -a Gimp desktop=^2 follow=on state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Virt-manager desktop=^3 follow=on state=floating
bspc rule -a obs desktop=^7 follow=on
bspc rule -a Zathura state=tiled
bspc rule -a SoulseekQt desktop=^3 follow=on
bspc rule -a FileZilla desktop=^6 follow=on
bspc rule -a Galculator state=floating
bspc rule -a Anki follow=on
bspc rule -a KeePassXC desktop=^5 follow=on
bspc rule -a firefoxdeveloperedition desktop=^1
bspc rule -a kanjitomo-reader-Launcher follow=on state=floating desktop=^3

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
