#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x blueman-applet || blueman-applet &
pgrep -x nm-applet || nm-applet &
numlockx on &
$HOME/.config/polybar/launch.sh
$HOME/.config/x11/xinitrc

### Monitors ###
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

### BSPWM config ###
bspc config border_width          2
bspc config window_gap            10
bspc config top_padding           30
bspc config bottom_padding        10
bspc config left_padding          10
bspc config right_padding         10
bspc config split_ratio           0.50
bspc config single_monocle        false
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# bspc config focus_by_distance     true
# bspc config click_to_focus        true
bspc config focus_follows_pointer true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"


# Rules for windows
bspc rule -a Gimp desktop=^8 follow=on state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Virt-manager desktop=^3 follow=on state=floating
bspc rule -a obs desktop=^7 follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Brave-browser desktop=^1
bspc rule -a Nicotine desktop=^3 follow=on
bspc rule -a Filezilla desktop=^6 follow=on
bspc rule -a Galculator state=floating


#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
